name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)
# Pipeline triggers on any branch and tag
trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'
pr:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      ref: docker-buildstamp
      endpoint: statisticsnorway

# Pipeline will be run on this base image
pool:
  vmImage: 'ubuntu-latest'

# Variables global to this pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
variables:
  # Variables defined in Pipelines->Library->Variable Groups in your project in
  # Azure Pipelines
  - group: Hemmeligheter
  # Variables defined here
  - name: appName
    value: 'dapla-start-api'
  - name: namespace
    value: 'dapla'
  - name: sonarCloud
    value: 'bipSonarCloud-Dapla'
  - name: buildTimestamp
    value: $[ format('{0:yyyyMMddHHmmss}', pipeline.startTime) ]
  - name: imageTagBeforeVulnerabilityScan
    value: 'imagescan-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(buildTimestamp)'
  - name: imageTagAfterVulnerabilityScan
    value: '$(Build.SourceBranchName)-$(Build.SourceVersion)-$(buildTimestamp)'


jobs:
  - template: python/python-complete-build.yml@templates
    parameters:
      appName: $(appName)
      namespace: $(namespace)
      sonarCloud: $(sonarCloud)
      snykOrganisation: statistikktjenester
      snykServiceConnection: azure-pipelines-snyk-statistikktjenester
      imageTagBeforeVulnerabilityScan: $(imageTagBeforeVulnerabilityScan)
      imageTagAfterVulnerabilityScan: $(imageTagAfterVulnerabilityScan)


  # Pull and retag docker image. Will only run if it is a tag-operation on the repo.
  # See https://github.com/statisticsnorway/azure-pipelines-templates/blob/master/docker/docker-tag-for-production.yml
  - template: docker/docker-tag-for-production.yml@templates
    parameters:
      tagToTag: 'master-$(Build.SourceVersion)-$(buildTimestamp)'
      gcrImageName: 'eu.gcr.io/prod-bip/ssb/$(namespace)/$(appName)'
