[tool.poetry]
name = "dapla-start-api"
version = "0.1.4"
description = ""
authors = ["Team Argus"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.70.1"
uvicorn = "^0.16.0"
PyGithub = "^1.55"
black = "^21.12b0"
isort = "^5.10.1"
cookiecutter = "^1.7.3"
requests = "^2.26.0"
cryptography = "^3.2"
prometheus-fastapi-instrumentator = "^5.7.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
mypy = "^0.910"
pudb = "^2021.2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
