[tool.poetry]
name = "dapla-start-api"
version = "0.2.1"
description = ""
authors = ["Team Argus"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.70.1"
uvicorn = "^0.16.0"
requests = "^2.26.0"
PyYAML = "^6.0"
prometheus-fastapi-instrumentator = "^5.7.1"
PyJWT = "^2.3.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
mypy = "^0.910"
pudb = "^2021.2.2"
jsonschema = "^4.4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
